### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by 77G0** [cctien/bimultialign#1]
what is python version?

**Comment by Zireaeel** [comment]
Hello, 

The latest python version is Python is 3.12.2, there were a lot of versions of python..

Python version refers to a specific version of the Python programming language that contains updates, bug fixes and new features, so we can encounter fewer bugs in new versions

If you want to check which version of Python do you have/installed on your system, write "python --version" on the command line (CMD). So you can learn which version you have.

**Comment by 77G0** [comment]
Thank you very much for your reply. Recently I have been reading this article, which is very good and makes me feel a lot. According to allennlp == 1.5.0, I downloaded the corresponding python=3.8 and Torch=1.6.0, thank you again for your reply！




32209082&nbsp;葛成武&nbsp;电信
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cctien/bimultialign"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月19日(星期天) 凌晨1:10
***@***.***&gt;;
抄送:&nbsp;"32209082 葛成武 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cctien/bimultialign] python version (Issue #1)





 
Hello,
 
The latest python version is Python is 3.12.2, there were a lot of versions of python..
 
Python version refers to a specific version of the Python programming language that contains updates, bug fixes and new features, so we can encounter fewer bugs in new versions
 
If you want to check which version of Python do you have/installed on your system, write "python --version" on the command line (CMD). So you can learn which version you have.

**Comment by 77G0** [comment]
Hello, I encountered such an error when running the code you provided, which should be unable to connect to the network, so I plan to download the model xlm-r manually. According to the error path, I could not find the specific location of the imported model, but I tried cache_directory, which failed. Could you please answer this question? Or how do we solve this problem, thank you very much
![QQ图片20240521110416](https://github.com/cctien/bimultialign/assets/126839492/6c4e6ea4-d97d-4c23-9893-2dc5beeea5b4)

**Comment by 77G0** [comment]
data/xlm/para   Are data downloads placed under the bimultialign file？

**Comment by cctien** [comment]
yeah. Please download XLM from their site, following their instruction on preprocessing (if applicable).
https://github.com/facebookresearch/XLM

and put them in the `data/xlm/para` inside this repo.
